baseURL = 'https://jackj.net/'
languageCode = 'en-us'
title = "Jack's Site"
theme = "hello-friend-ng"
paginate = 10

[params]
  homeSubtitle = "Jack's (very work in progress) personal website!"
  description = "My new homepage"
  keywords = "homepage, blog"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"
